import random

APP_VERSION = "376.0.0.2.109"
VERSION_CODE = "719982544"

DEVICES = {
    # OnePlus Devices
    "one_plus_7": {
        "app_version": APP_VERSION,
        "android_version": "29",
        "android_release": "10.0",
        "dpi": "420dpi",
        "resolution": "1080x2340",
        "manufacturer": "OnePlus",
        "device": "GM1903",
        "model": "OnePlus7",
        "cpu": "qcom",
        "version_code": VERSION_CODE,
    },
    "one_plus_3": {
        "app_version": APP_VERSION,
        "android_version": "28",
        "android_release": "9.0",
        "dpi": "420dpi",
        "resolution": "1080x1920",
        "manufacturer": "OnePlus",
        "device": "ONEPLUS A3003",
        "model": "OnePlus3",
        "cpu": "qcom",
        "version_code": VERSION_CODE,
    },
    "one_plus_3t": {
        "app_version": APP_VERSION,
        "android_version": "26",
        "android_release": "8.0",
        "dpi": "380dpi",
        "resolution": "1080x1920",
        "manufacturer": "OnePlus",
        "device": "ONEPLUS A3010",
        "model": "OnePlus3T",
        "cpu": "qcom",
        "version_code": VERSION_CODE,
    },

    # Samsung Devices
    "samsung_galaxy_s7": {
        "app_version": APP_VERSION,
        "android_version": "26",
        "android_release": "8.0",
        "dpi": "640dpi",
        "resolution": "1440x2560",
        "manufacturer": "samsung",
        "device": "SM-G930F",
        "model": "herolte",
        "cpu": "samsungexynos8890",
        "version_code": VERSION_CODE,
    },
    "samsung_galaxy_s9_plus": {
        "app_version": APP_VERSION,
        "android_version": "28",
        "android_release": "9.0",
        "dpi": "640dpi",
        "resolution": "1440x2560",
        "manufacturer": "samsung",
        "device": "SM-G965F",
        "model": "star2qltecs",
        "cpu": "samsungexynos9810",
        "version_code": VERSION_CODE,
    },
    "samsung_galaxy_s7_edge": {
        "app_version": APP_VERSION,
        "android_version": "23",
        "android_release": "6.0.1",
        "dpi": "640dpi",
        "resolution": "1440x2560",
        "manufacturer": "samsung",
        "device": "SM-G935",
        "model": "hero2lte",
        "cpu": "samsungexynos8890",
        "version_code": VERSION_CODE,
    },
    "samsung_galaxy_s24_ultra": {
        "app_version": APP_VERSION,
        "android_version": "34",
        "android_release": "14.0",
        "dpi": "500dpi",
        "resolution": "1440x3120",
        "manufacturer": "samsung",
        "device": "SM-S928B",
        "model": "Galaxy S24 Ultra",
        "cpu": "qcom",
        "version_code": VERSION_CODE,
    },

    # Huawei
    "huawei_mate_9_pro": {
        "app_version": APP_VERSION,
        "android_version": "24",
        "android_release": "7.0",
        "dpi": "640dpi",
        "resolution": "1440x2560",
        "manufacturer": "HUAWEI",
        "device": "LON-L29",
        "model": "HWLON",
        "cpu": "hi3660",
        "version_code": VERSION_CODE,
    },

    # LG
    "lg_g5": {
        "app_version": APP_VERSION,
        "android_version": "23",
        "android_release": "6.0.1",
        "dpi": "640dpi",
        "resolution": "1440x2392",
        "manufacturer": "LGE/lge",
        "device": "RS988",
        "model": "h1",
        "cpu": "h1",
        "version_code": VERSION_CODE,
    },

    # ZTE
    "zte_axon_7": {
        "app_version": APP_VERSION,
        "android_version": "23",
        "android_release": "6.0.1",
        "dpi": "640dpi",
        "resolution": "1440x2560",
        "manufacturer": "ZTE",
        "device": "ZTE A2017U",
        "model": "ailsa_ii",
        "cpu": "qcom",
        "version_code": VERSION_CODE,
    },

    # Xiaomi
    "xiaomi_redmi_note_10_pro": {
        "app_version": APP_VERSION,
        "android_version": "30",
        "android_release": "11.0",
        "dpi": "440dpi",
        "resolution": "1080x2400",
        "manufacturer": "Xiaomi",
        "device": "sweet",
        "model": "Redmi Note 10 Pro",
        "cpu": "qcom",
        "version_code": VERSION_CODE,
    },
    "xiaomi_14_pro": {
        "app_version": APP_VERSION,
        "android_version": "34",
        "android_release": "14.0",
        "dpi": "520dpi",
        "resolution": "1440x3200",
        "manufacturer": "Xiaomi",
        "device": "Xiaomi 23116PN5BC",
        "model": "Xiaomi 14 Pro",
        "cpu": "qcom",
        "version_code": VERSION_CODE,
    },

    # Realme
    "realme_c25": {
        "app_version": APP_VERSION,
        "android_version": "30",
        "android_release": "11.0",
        "dpi": "320dpi",
        "resolution": "720x1600",
        "manufacturer": "realme",
        "device": "RMX3191",
        "model": "RMX3191",
        "cpu": "mt6768",
        "version_code": VERSION_CODE,
    },
    "realme_gt_5_pro": {
        "app_version": APP_VERSION,
        "android_version": "34",
        "android_release": "14.0",
        "dpi": "480dpi",
        "resolution": "1264x2780",
        "manufacturer": "realme",
        "device": "RMX3888",
        "model": "realme GT 5 Pro",
        "cpu": "qcom",
        "version_code": VERSION_CODE,
    },

    # Asus
    "asus_rog_phone_5": {
        "app_version": APP_VERSION,
        "android_version": "30",
        "android_release": "11.0",
        "dpi": "480dpi",
        "resolution": "1080x2448",
        "manufacturer": "asus",
        "device": "ZS673KS",
        "model": "ROG Phone 5",
        "cpu": "qcom",
        "version_code": VERSION_CODE,
    },
    "asus_zenfone_11_ultra": {
        "app_version": APP_VERSION,
        "android_version": "34",
        "android_release": "14.0",
        "dpi": "480dpi",
        "resolution": "2400x1080",
        "manufacturer": "asus",
        "device": "ASUS_AI2401_H",
        "model": "Zenfone 11 Ultra",
        "cpu": "qcom",
        "version_code": VERSION_CODE,
    },

    # Vivo
    "vivo_y20": {
        "app_version": APP_VERSION,
        "android_version": "30",
        "android_release": "11.0",
        "dpi": "270dpi",
        "resolution": "720x1600",
        "manufacturer": "vivo",
        "device": "vivo 2027",
        "model": "vivo 2027",
        "cpu": "mt6768",
        "version_code": VERSION_CODE,
    },
    "vivo_x100_pro": {
        "app_version": APP_VERSION,
        "android_version": "34",
        "android_release": "14.0",
        "dpi": "480dpi",
        "resolution": "1260x2800",
        "manufacturer": "vivo",
        "device": "PD2319",
        "model": "vivo X100 Pro",
        "cpu": "mediatek",
        "version_code": VERSION_CODE,
    },

    # OPPO
    "oppo_find_x7_ultra": {
        "app_version": APP_VERSION,
        "android_version": "34",
        "android_release": "14.0",
        "dpi": "520dpi",
        "resolution": "1440x3168",
        "manufacturer": "OPPO",
        "device": "PHZ110",
        "model": "OPPO Find X7 Ultra",
        "cpu": "qcom",
        "version_code": VERSION_CODE,
    },

    # Google
    "google_pixel_8_pro": {
        "app_version": APP_VERSION,
        "android_version": "34",
        "android_release": "14.0",
        "dpi": "490dpi",
        "resolution": "1344x2992",
        "manufacturer": "Google",
        "device": "husky",
        "model": "Pixel 8 Pro",
        "cpu": "google_tensor",
        "version_code": VERSION_CODE,
    },

    # Infinix
    "infinix_hot_10": {
        "app_version": APP_VERSION,
        "android_version": "30",
        "android_release": "11.0",
        "dpi": "320dpi",
        "resolution": "720x1640",
        "manufacturer": "Infinix",
        "device": "Infinix X682B",
        "model": "Infinix HOT 10",
        "cpu": "mt6768",
        "version_code": VERSION_CODE,
    },
    "infinix_zero_30_5g": {
        "app_version": APP_VERSION,
        "android_version": "33",
        "android_release": "13.0",
        "dpi": "480dpi",
        "resolution": "1080x2400",
        "manufacturer": "Infinix",
        "device": "X6731B",
        "model": "Infinix Zero 30 5G",
        "cpu": "mtk",
        "version_code": VERSION_CODE,
    },

    # Tecno
    "tecno_phantom_v_flip": {
        "app_version": APP_VERSION,
        "android_version": "33",
        "android_release": "13.0",
        "dpi": "480dpi",
        "resolution": "1080x2460",
        "manufacturer": "TECNO",
        "device": "AD11",
        "model": "Phantom V Flip",
        "cpu": "mtk",
        "version_code": VERSION_CODE,
    },
    # Samsung Devices
"samsung_galaxy_z_fold_3": {
    "app_version": APP_VERSION,
    "android_version": "30",
    "android_release": "11.0",
    "dpi": "374dpi",
    "resolution": "1768x2208",
    "manufacturer": "samsung",
    "device": "SM-F926B",
    "model": "Galaxy Z Fold 3",
    "cpu": "samsungexynos2100",
    "version_code": VERSION_CODE,
},

# Huawei
"huawei_p50_pro": {
    "app_version": APP_VERSION,
    "android_version": "30",
    "android_release": "11.0",
    "dpi": "450dpi",
    "resolution": "1228x2700",
    "manufacturer": "HUAWEI",
    "device": "HWI-AN00",
    "model": "P50 Pro",
    "cpu": "kirin9000",
    "version_code": VERSION_CODE,
},

# LG
"lg_v60_thinq": {
    "app_version": APP_VERSION,
    "android_version": "30",
    "android_release": "11.0",
    "dpi": "395dpi",
    "resolution": "1080x2460",
    "manufacturer": "LGE/lge",
    "device": "LM-V600EM",
    "model": "LG V60 ThinQ",
    "cpu": "qcom",
    "version_code": VERSION_CODE,
},

# Realme
"realme_8_pro": {
    "app_version": APP_VERSION,
    "android_version": "30",
    "android_release": "11.0",
    "dpi": "409dpi",
    "resolution": "1080x2400",
    "manufacturer": "realme",
    "device": "RMX3081",
    "model": "Realme 8 Pro",
    "cpu": "qcom",
    "version_code": VERSION_CODE,
},

# Asus
"asus_zenfone_8": {
    "app_version": APP_VERSION,
    "android_version": "30",
    "android_release": "11.0",
    "dpi": "440dpi",
    "resolution": "1080x2400",
    "manufacturer": "asus",
    "device": "ZS590KS",
    "model": "Zenfone 8",
    "cpu": "qcom",
    "version_code": VERSION_CODE,
},

# Tecno
"tecno_spark_8": {
    "app_version": APP_VERSION,
    "android_version": "30",
    "android_release": "11.0",
    "dpi": "270dpi",
    "resolution": "720x1600",
    "manufacturer": "TECNO",
    "device": "TECNO SPARK 8",
    "model": "TECNO Spark 8",
    "cpu": "mt6765",
    "version_code": VERSION_CODE,
},

# Infinix
"infinix_note_11": {
    "app_version": APP_VERSION,
    "android_version": "30",
    "android_release": "11.0",
    "dpi": "270dpi",
    "resolution": "720x1640",
    "manufacturer": "Infinix",
    "device": "Infinix X6813",
    "model": "Infinix Note 11",
    "cpu": "mt6765",
    "version_code": VERSION_CODE,
},

# Vivo
"vivo_y33s": {
    "app_version": APP_VERSION,
    "android_version": "30",
    "android_release": "11.0",
    "dpi": "270dpi",
    "resolution": "720x1600",
    "manufacturer": "vivo",
    "device": "V2101",
    "model": "Vivo Y33s",
    "cpu": "mt6769",
    "version_code": VERSION_CODE,
},

# OPPO
"oppo_a74": {
    "app_version": APP_VERSION,
    "android_version": "30",
    "android_release": "11.0",
    "dpi": "409dpi",
    "resolution": "1080x2400",
    "manufacturer": "OPPO",
    "device": "CPH2219",
    "model": "OPPO A74",
    "cpu": "qcom",
    "version_code": VERSION_CODE,
},

# Google
"google_pixel_6a": {
    "app_version": APP_VERSION,
    "android_version": "32",
    "android_release": "12.0",
    "dpi": "415dpi",
    "resolution": "1080x2400",
    "manufacturer": "Google",
    "device": "bluejay",
    "model": "Pixel 6a",
    "cpu": "google_tensor",
    "version_code": VERSION_CODE,
},

# Sony
"sony_xperia_1_iii": {
    "app_version": APP_VERSION,
    "android_version": "30",
    "android_release": "11.0",
    "dpi": "643dpi",
    "resolution": "1644x3840",
    "manufacturer": "Sony",
    "device": "XQ-BC72",
    "model": "Xperia 1 III",
    "cpu": "qcom",
    "version_code": VERSION_CODE,
},

# Motorola
"motorola_edge_20": {
    "app_version": APP_VERSION,
    "android_version": "30",
    "android_release": "11.0",
    "dpi": "393dpi",
    "resolution": "1080x2400",
    "manufacturer": "Motorola",
    "device": "XT2143-1",
    "model": "Edge 20",
    "cpu": "qcom",
    "version_code": VERSION_CODE,
},

# Nokia
"nokia_g50": {
    "app_version": APP_VERSION,
    "android_version": "30",
    "android_release": "11.0",
    "dpi": "270dpi",
    "resolution": "720x1600",
    "manufacturer": "Nokia",
    "device": "Nokia G50",
    "model": "Nokia G50",
    "cpu": "qcom",
    "version_code": VERSION_CODE,
},

# Honor
"honor_50": {
    "app_version": APP_VERSION,
    "android_version": "30",
    "android_release": "11.0",
    "dpi": "410dpi",
    "resolution": "1080x2400",
    "manufacturer": "Honor",
    "device": "HJC-AN00",
    "model": "Honor 50",
    "cpu": "qcom",
    "version_code": VERSION_CODE,
},

# ZTE
"zte_axon_20": {
    "app_version": APP_VERSION,
    "android_version": "30",
    "android_release": "11.0",
    "dpi": "400dpi",
    "resolution": "1080x2400",
    "manufacturer": "ZTE",
    "device": "ZTE A2020G1",
    "model": "Axon 20",
    "cpu": "qcom",
    "version_code": VERSION_CODE,
},

# Tecno
"tecno_pop_5": {
    "app_version": APP_VERSION,
    "android_version": "30",
    "android_release": "11.0",
    "dpi": "270dpi",
    "resolution": "720x1600",
    "manufacturer": "TECNO",
    "device": "TECNO POP 5",
    "model": "TECNO Pop 5",
    "cpu": "mt6761",
    "version_code": VERSION_CODE,
},
}

DEFAULT_DEVICE = list(DEVICES.keys())
